HEATING_BOUND_MIN = 18.0
HEATING_BOUND_MAX = 22.0
COOLING_BOUND_MIN = 23.0
COOLING_BOUND_MAX = 27.0
MIN_DEADBAND = 1.0

COMFORT_HEATING = 22.0
COMFORT_COOLING = 24.0
COMFORT_TOLERANCE = 0.5
COMFORT_TRIGGER_LOW = COMFORT_HEATING - COMFORT_TOLERANCE
COMFORT_TRIGGER_HIGH = COMFORT_COOLING + COMFORT_TOLERANCE

NORMAL_STEP = 0.5
AGGRESSIVE_STEP = 1.0
AGGRESSIVE_ENTRY_THRESHOLD = 2.0
AGGRESSIVE_EXIT_THRESHOLD = 1.5

DWELL_CYCLES = 4
INITIALIZING_TIMEOUT_CYCLES = 10
SATURATION_CYCLE_THRESHOLD = 8

ZONE_NAMES = ["SPACE1-1", "SPACE2-1", "SPACE3-1", "SPACE4-1", "SPACE5-1"]

READBACK_TOLERANCE = 0.001
READBACK_FAILURE_LIMIT = 3

SENSOR_TEMP_FLOOR = -50.0
SENSOR_TEMP_CEILING = 60.0

STATE_IDLE = "IDLE"
STATE_HEATING = "HEATING"
STATE_COOLING = "COOLING"
STATE_DEGRADED = "DEGRADED"

STATUS_INITIALIZING = "INITIALIZING"
STATUS_RUNNING = "RUNNING"
STATUS_STOPPED = "STOPPED"
STATUS_DISABLED = "DISABLED"
